### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by sterichards** [soft-industry/docker-compose-php#1]
E: Package 'libpng12-dev' has no installation candidate
ERROR: Service 'phpfpm' failed to build : The command '/bin/sh -c apt-get update && apt-get install -y 	libmcrypt-dev  	libicu-dev 	mysql-client     libfreetype6-dev     libjpeg62-turbo-dev     libpng12-dev 	&& docker-php-ext-install pdo_mysql 	&& docker-php-ext-install iconv 	&& docker-php-ext-install mcrypt 	&& docker-php-ext-install intl 	&& docker-php-ext-install opcache 	&& docker-php-ext-install mbstring     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gd' returned a non-zero code: 100

**Comment by Danbut** [comment]
You need to change libpng12-dev to libpng-dev in the Dockerfile, which is located in the php-fpm-5.6 directory.

**Comment by skoro** [comment]
Thanks! Fixed in 8b2d2c8
